#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions
application=$(sed -ne "s/^application\s*\(.*\);/\1/p" system/controlDict)

runApplication blockMesh
restore0Dir
runApplication initAlphaField
touch velocity.foam

runApplication $(getApplication)
#decomposePar
#sbatch Allrun.slurm

