#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions
application=$(sed -ne "s/^application\s*\(.*\);/\1/p" system/controlDict)
wmake libso generateUVortex2D

runApplication blockMesh
restore0Dir

runApplication setAlphaField
runApplication generateUVortex2D
runApplication $(getApplication)

cp postProcessing/volumeFractionError/0/volumeFractionError.dat volumeFractionError.dat
rm -r postProcessing
runApplication decomposePar
mpirun -oversubscribe -np 4 $(getApplication) -parallel  > log.$(getApplication).par
cp postProcessing/volumeFractionError/0/volumeFractionError.dat volumeFractionErrorPar.dat
