#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

. $WM_PROJECT_DIR/bin/tools/RunFunctions
application=$(sed -ne "s/^application\s*\(.*\);/\1/p" system/controlDict)

touch deform.foam
wmake libso generateUDeform

runApplication blockMesh
restore0Dir

runApplication setAlphaField
runApplication generateUDeform

runApplication decomposePar
mpirun -oversubscribe -np 4 $(getApplication) -parallel  > log.$(getApplication)
cp postProcessing/volumeFractionError/0/volumeFractionError.dat volumeFractionError.dat
