name: openfoam

on:
  push:
    branches: [ of2406 ]
  pull_request:
    branches: [ of2406 ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up OpenFOAM
      uses: gerlero/setup-openfoam@v1
      with:
        openfoam-version: 2406

    - name: Install dependencies
      uses: gerlero/apt-install@v1
      with:
        packages: >-
          libomp-16-dev
          python3
          python3-dev
          build-essential
          libopenmpi-dev
          openmpi-bin

    - name: compile library
      run: |
        export WM_NCOMPPROCS=2
        openfoam2406 -c ./Allwmake
        openfoam2406 -c ./get-gmsh.sh
    - name: test
      run: |
        python -m pip install --upgrade pip
        pip install oftest scipy casefoam
        openfoam2406 -c "py.test  --writeNSteps=1 run/"
        openfoam2406 -c "py.test -m 'not slow'"
        
    - name: upload logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs
