name: openfoam

on:
  push:
    branches: [ of2106 ]
  pull_request:
    branches: [ of2106 ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup  openfoam
      run: |
        curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        sudo apt-get install openfoam2106-dev
    - name: compile library
      run: |
        export WM_NCOMPPROCS=2
        openfoam2106 -c ./Allwmake
    - name: test
      run: |
        python -m pip install --upgrade pip
        pip install oftest scipy casefoam
        openfoam2106 -c py.test -m "not slow" --tb=auto -v
